// frontend-vue/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'

const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:8080'
const health = ref<string>('Sprawdzam API...')

onMounted(async () => {
  try {
    const response = await fetch(`${apiUrl}/api/health`)
    const data = await response.json()
    health.value = `Backend: ${data.status} (PHP ${data.php})`
  } catch {
    health.value = 'Backend niedostępny'
  }
})
</script>

<template>
  <main class="page">
    <h1>TaxInvest</h1>
    <p>Frontend Vue 3 + Vite</p>
    <p class="status">{{ health }}</p>
  </main>
</template>

<style scoped>
.page {
  font-family: system-ui, sans-serif;
  max-width: 640px;
  margin: 4rem auto;
  padding: 0 1rem;
}

.status {
  color: #2563eb;
}
</style>

// frontend-next/src/app/page.tsx
async function getHealth() {
  const apiUrl =
    process.env.API_URL_INTERNAL ??
    process.env.NEXT_PUBLIC_API_URL ??
    'http://localhost:8080'

  try {
    const response = await fetch(`${apiUrl}/api/health`, { cache: 'no-store' })
    if (!response.ok) {
      return 'Backend niedostępny'
    }

    const data = (await response.json()) as { status: string; php: string }
    return `Backend: ${data.status} (PHP ${data.php})`
  } catch {
    return 'Backend niedostępny'
  }
}

export default async function HomePage() {
  const health = await getHealth()

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', maxWidth: 640, margin: '4rem auto', padding: '0 1rem' }}>
      <h1>TaxInvest</h1>
      <p>Frontend Next.js (React)</p>
      <p style={{ color: '#2563eb' }}>{health}</p>
    </main>
  )
}
